### ISSUE TITLE
Work Experience in Nav Bar

### ISSUE THREAD

**Issue by zmwieand** [michaelkulbacki/michaelkulbacki.github.io#4]
redirects to "<url>#projects"
Do you not want people to know where you have worked?

**Comment by michaelkulbacki** [comment]
Work experience tab is within the Projects/ experience bar on the home page (try reading little more carefully :) )

**Comment by zmwieand** [comment]
When I click on the tab in the nav bar from the courses.html page I am redirected from:
http://michaelkulbacki.github.io/courses.html -> http://michaelkulbacki.github.io/courses.html#projects

same idea from the About page

I want to know where you have worked, please redirect me to the appropriate page.

**Comment by michaelkulbacki** [comment]
Well that would require me to code that page, as you know this website is under construction so I haven't completed every page yet sir.  I apologize that I am not working faster!
